// src/components/Canvas3D.svelte
<script lang="ts">
    import { onMount } from 'svelte'; // eslint-disable-line
    import MatcapPreviewWorld from '../matcapPreview/MatcapPreviewWorld';
    import MatcapEditorWorld from '../matcapEditor/MatcapEditorWorld';
    import { MatcapEditorStore } from '../store';
    import type { IMatcapEditorStore } from '../store';
    import MatcapLights from './MatcapLights.svelte';
    import PreviewProperties from './PreviewProperties.svelte';
    import CanvasSnapshots from './CanvasSnapshots.svelte';
    import Editor from 'src/Editor';

    // Force reload

    if (import.meta.hot) {
        import.meta.hot.dispose(() => {
            import.meta.hot.invalidate();
        });
    }

    let store: IMatcapEditorStore;
    MatcapEditorStore.subscribe((value) => {
        store = value;
    });

    onMount(() => {
        const editor = new Editor();
        const worldPreview = new MatcapPreviewWorld(editor);
        worldPreview.init();
        const worldEditor = new MatcapEditorWorld(editor);
        worldEditor.init();
    });
</script>

<CanvasSnapshots />
<canvas class="webgl" />
<canvas class="webgl2" width={String(store.sizes.exportDefault)} height={String(store.sizes.exportDefault)} />
<MatcapLights />

<PreviewProperties />

<style>
    .webgl {
        outline: none;
        background-color: white;
    }
    .webgl2 {
        position: absolute;
        top: 0;
        right: 0;
        outline: none;
        background-color: black;
        width: 200px !important;
        height: 200px !important;
        border: 1px solid white;
    }
</style>

// src/components/Canvas3D.vue
<template >
    <CanvasSnapshots />
    <canvas class="webgl" 
        @dragover.prevent=""
        @drop.prevent="DroppedFileManager.onDrop" 
    />
    <canvas class="webgl2"
        :width="String(store.sizes.view)"
        :height="String(store.sizes.view)"
        :style="getStyles()"
    />
    <MatcapLights />

    <PreviewProperties />

</template >

<script lang="ts" setup >

import Editor from '@/Editor';
import { matcapEditorStore } from '@/stores/matcapEditorStore';
import { onMounted, computed } from 'vue';
import MatcapLights from './MatcapLights.vue';
import CanvasSnapshots from './CanvasSnapshots.vue';
import PreviewProperties from './PreviewProperties.vue';
import { ref } from 'vue';
import DroppedFileManager from '@/commons/DroppedFileManager';

if (import.meta.hot) {
    import.meta.hot.dispose(() => {
        import.meta.hot?.invalidate();
    });
}

const store = computed(() => matcapEditorStore());
const canvas_preview = ref(null);
let editor: Editor;

onMounted(async () => {
    editor = Editor.instance;
});

function getStyles() {
    return `
        width: ${store.value.sizes.view}px!important;
        height: ${store.value.sizes.view}px!important;
    `;
}

async function onDrop(event: DragEvent) {
    const file = event.dataTransfer?.files[0];
    console.log(file);
    
    // const fileContent = await promiseReader(file);
    // console.log(fileContent);
    // const blob = new Blob([fileContent], { type: 'image/png' });
    // const url = URL.createObjectURL(blob);
    // const image = new Image();
    // image.src = url;
    // image.onload = () => {
    //     matcapEditorStore().setMatcap(image);
    // };
    
}



</script >
