// src/components/MatcapLights.svelte
<script lang="ts">
    import { MatcapEditorStore, type IMatcapEditorStore } from 'src/store';
    import events from 'src/commons/Events';
    import type LightModel from 'src/matcapEditor/LightModel';
    import MatcapProperties from './MatcapProperties.svelte';

    if (import.meta.hot) {
        import.meta.hot.dispose(() => {
            import.meta.hot.invalidate();
        });
    }
    let store: IMatcapEditorStore;
    MatcapEditorStore.subscribe((newStore) => {
        store = newStore;
    });

    let currentLight: LightModel = null;

    const lightAdded = (lightModel: LightModel): void => {
        currentLight = lightModel;
        events.emit('matcap:light:update:current', lightModel);
        store.lights.push(lightModel);
    };

    $: getMatcapLightsStyle = () => `
            width: ${store.sizes.view}px;
            height: ${store.sizes.view}px;
        `;

    $: getCSSPosition = (lightModel: LightModel) => `
            left:${lightModel.screenPosition.x / store.ratio - 6}px;
            top:${lightModel.screenPosition.y / store.ratio - 6}px;
            border-color:${lightModel.light.uuid === currentLight.light.uuid ? '#00ffff' : '#ffffff'};
        `;

    const onMouseDown = (lightModel: LightModel): void => {
        store.isUILightVisible = false;
        currentLight = lightModel;
        events.emit('matcap:light:update:current', lightModel);
        events.emit('matcap:light:startMoving', lightModel);
    };

    events.on('matcap:editor:light:added', lightAdded);
</script>

<div>
    {#if store.isUILightVisible}
        <div id="matcapLights" style={getMatcapLightsStyle()}>
            {#each store.lights as light}
                <div class="light" style={getCSSPosition(light)} on:mousedown={() => onMouseDown(light)} />
            {/each}
        </div>
    {/if}
    <MatcapProperties />
</div>

<style>
    #matcapLights {
        position: absolute;
        top: 0;
        right: 0;
        pointer-events: none;
    }
    .light {
        position: absolute;
        background-color: black;
        width: 10px;
        height: 10px;
        border-radius: 10px;
        touch-action: none;
        pointer-events: all;
        border-width: 1px;
        border-style: solid;
        mix-blend-mode: difference;
        cursor: pointer;
    }
    .light:hover {
        background-color: rgba(255, 255, 255, 0.233);
    }
</style>

// src/components/MatcapLights.vue
<template >
    <div id="matcapLights"
        :style="getMatcapLightsStyle()"
        v-if="store.isUILightVisible" 
    >
        <div v-for="light, index in store.lights"
            :key="index"
            :style="getCSSPosition(light as LightModel)"
            class="light"
            @mousedown="onMouseDown(light as LightModel)" >
        </div >
    </div >
    <MatcapProperties />
</template >

<script lang="ts" setup >
import events from '@/commons/Events';
import type LightModel from '@/matcapEditor/LightModel';
import { computed } from 'vue';
import { matcapEditorStore } from '@/stores/matcapEditorStore';
import MatcapProperties from './MatcapProperties.vue';

if (import.meta.hot) {
    import.meta.hot.dispose(() => {
        import.meta?.hot?.invalidate();
    });
}

const store = computed(() => matcapEditorStore());
let currentLight: LightModel;

const lightAdded = (lightModel: LightModel): void => {
    currentLight = lightModel;
    events.emit('matcap:light:update:current', lightModel);
    store.value.addLight(lightModel);
};

function getMatcapLightsStyle() {
    return `
        width: ${store.value.sizes.view}px;
        height: ${store.value.sizes.view}px;
    `;
}

function getCSSPosition(lightModel: LightModel) {
    return `
        left:${lightModel.screenPosition.x / store.value.ratio - 6}px;
        top:${lightModel.screenPosition.y / store.value.ratio - 6}px;
        border-color:${lightModel.light.uuid === currentLight.light.uuid ? '#00ffff' : '#ffffff'};
    `;
}

const onMouseDown = (lightModel: LightModel): void => {
    store.value.isUILightVisible = false;
    currentLight = lightModel;
    events.emit('matcap:light:update:current', lightModel);
    events.emit('matcap:light:startMoving', lightModel);
};

events.on('matcap:ui:light:update:current', (lightModel: LightModel) => {
    currentLight = lightModel;
});

events.on('matcap:editor:light:added', lightAdded);
events.on('matcap:editor:light:remove', (lightModel: LightModel) => {
    store.value.removeLight(lightModel);
});
</script >
